### PR TITLE
Add styling, animations, and icons to the to-do list UI

### PR DESCRIPTION
**Pull request by BAHLEMAJOLA**
Added a background gradient and animation to the page for a more modern look.
Included Font Awesome icons for the "Add Task", "Complete", and "Delete" buttons.
Created a separate section to display completed tasks with distinct styling.
Added a fade-in animation for new tasks that improves the user experience.
Improved the task action buttons with hover effects and color changes.
# dev branch p

### CODE REVIEW

**Comment by BAHLEMAJOLA** [comment]
@Sinawo 
@NuffSaid-Bore 
@zolwethu 
Hi everyone,

I've just submitted a pull request with my latest changes. Could you please take a moment to review it? Your feedback would be greatly appreciated!

Thanks in advance!

**Review by Sinawo — CHANGES_REQUESTED** [review]
Amazing work @BAHLEMAJOLA, can you please include an edit button so that a user is able to edit a task name.

**Review by zolwethu — CHANGES_REQUESTED** [review]
@BAHLEMAJOLA  Set up a file for node js. And use ES Modules `import` instead of "require". There's no need to use `export` in this case, as you're simply setting up a server, but it was included in the instructions.

**Review by zolwethu — APPROVED** [review]
@BAHLEMAJOLA Baie danke, these are the some key characteristics of "import":

The import statement is asynchronous, allowing other operations to run while the module is being fetched. Also allows for importing specific functions or variables from a module and unlike "require", the import statement doesn't cache modules, resulting in a fresh instance every time it is imported.

**Pull request merged**
